# -*- coding: utf-8 -*-
"""unsupervized clustering

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/#fileId=https%3A//storage.googleapis.com/kaggle-colab-exported-notebooks/unsupervized-clustering-9a797187-ed5a-4fd0-8934-bb326f2d308a.ipynb%3FX-Goog-Algorithm%3DGOOG4-RSA-SHA256%26X-Goog-Credential%3Dgcp-kaggle-com%2540kaggle-161607.iam.gserviceaccount.com/20250316/auto/storage/goog4_request%26X-Goog-Date%3D20250316T180410Z%26X-Goog-Expires%3D259200%26X-Goog-SignedHeaders%3Dhost%26X-Goog-Signature%3D8d056b5add27dedf2bbc7d7bd7e58996e015e9167d12cb136f32fecc24ad44db174974270bd1f81e150ee02df11ce998640b2ae3f527f6ee679663dd5415da9e16b5cfb49025ac5a76b73adccc31698fe123cbf0a7da335eaa18718576483e6a286eeea6c1f5af76f2cf919c4df654b0e197b9a851b20a01526ee7f7df990fa63c94ff28f518369c4994aefef4600c85a32e42c28583cb2eee788f0b1022d5f1b52c2de2b4916960fb0c43669a5131a2aba3bae6fe591e50741824a7cf0da4106a784c03685b6c5b0bd27d3ae4f570211a83f2c2a61af619b7099d4ad70ab3147304a273a5e77790da1def09bed72bacdebbf34f41dc15b3612ce99751677d33
"""

# IMPORTANT: SOME KAGGLE DATA SOURCES ARE PRIVATE
# RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES.
import kagglehub
kagglehub.login()

# IMPORTANT: RUN THIS CELL IN ORDER TO IMPORT YOUR KAGGLE DATA SOURCES,
# THEN FEEL FREE TO DELETE THIS CELL.
# NOTE: THIS NOTEBOOK ENVIRONMENT DIFFERS FROM KAGGLE'S PYTHON
# ENVIRONMENT SO THERE MAY BE MISSING LIBRARIES USED BY YOUR
# NOTEBOOK.

omidudulen_test_d_path = kagglehub.dataset_download('omidudulen/test-d')
omidudulen_family_cluster_path = kagglehub.dataset_download('omidudulen/family-cluster')
omidudulen_omidu123_path = kagglehub.dataset_download('omidudulen/omidu123')
omidudulen_messi12_path = kagglehub.dataset_download('omidudulen/messi12')
omidudulen_wedana_path = kagglehub.dataset_download('omidudulen/wedana')

print('Data source import complete.')

"""#Installing face-recognition library"""

!pip3 install face_recognition

"""#Importing required libraries"""

import os
import pickle
import numpy as np
import cv2

from PIL import Image
from imutils import paths, build_montages
from sklearn.cluster import KMeans, DBSCAN
import face_recognition

"""#Demo to test face-recognition in Colab"""

# Path to image
image = face_recognition.load_image_file("/kaggle/input/family-cluster/family.jpg")
face_locations = face_recognition.face_locations(image)

display(image)

print("I found {} face(s) in this photograph.".format(len(face_locations)))

for face_location in face_locations:

    # Print the location of each face in this image
    top, right, bottom, left = face_location
    print("A face is located at pixel location Top: {}, Left: {}, Bottom: {}, Right: {}".format(top, left, bottom, right))

    # You can access the actual face itself like this:
    face_image = image[top:bottom, left:right]
    pil_image = Image.fromarray(face_image)
    display(pil_image)

"""#Creating encodings for the dataset"""

import os
import cv2
import pickle
import face_recognition
import matplotlib.pyplot as plt
from imutils import paths

# Specify paths
dataset_path = "/kaggle/input/test-d"
encodings_path = "/content/encodings.pickle"

# Initialize variables
data = []

# Get image paths from the dataset directory
imagePaths = list(paths.list_images(dataset_path))

# Loop over the image paths
for (i, imagePath) in enumerate(imagePaths):
    print(f"[INFO] Processing image {i + 1}/{len(imagePaths)}: {imagePath}")

    # Read the image
    image = cv2.imread(imagePath)
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Detect faces
    boxes = face_recognition.face_locations(rgb_image, model='hog')

    # Compute facial encodings
    encodings = face_recognition.face_encodings(rgb_image, boxes)

    # Store encodings in a dictionary
    for (box, enc) in zip(boxes, encodings):
        data.append({"imagePath": imagePath, "loc": box, "encoding": enc})

    # Draw face boxes
    for (top, right, bottom, left) in boxes:
        cv2.rectangle(rgb_image, (left, top), (right, bottom), (0, 255, 0), 3)

    # Display the image
    plt.figure(figsize=(6, 6))
    plt.imshow(rgb_image)
    plt.axis("off")
    plt.title(f"Image {i + 1}")
    plt.show()

# Save encodings to file
with open(encodings_path, "wb") as f:
    pickle.dump(data, f)

print(f"[INFO] Encodings saved to: {encodings_path}")

"""# Clustering with kmeans"""

import os
import cv2
import pickle
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from imutils import build_montages

# Specify paths
ENCODINGS_PATH = "/content/encodings.pickle"
CLUSTERING_RESULT_PATH = "/kaggle/working/"

# Create Clustering Results directory if it doesn't exist
if not os.path.exists(CLUSTERING_RESULT_PATH):
    os.mkdir(CLUSTERING_RESULT_PATH)

# Load encodings
print("[INFO] Loading encodings...")
data = pickle.load(open(ENCODINGS_PATH, "rb"))

# Extract encodings from data
encodings = np.array([d["encoding"] for d in data])

# Perform KMeans clustering
print("[INFO] Clustering...")
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)  # Adjust clusters if needed
labels = kmeans.fit_predict(encodings)

# Determine unique label IDs
labelIDs = np.unique(labels)
numUniqueFaces = len(labelIDs)
print(f"[INFO] Unique faces detected: {numUniqueFaces}")

# Loop over unique label IDs
for labelID in labelIDs:
    print(f"[INFO] Faces for cluster: {labelID}")
    idxs = np.where(labels == labelID)[0]
    idxs = np.random.choice(idxs, size=min(25, len(idxs)), replace=False)

    # Initialize list of faces
    faces = []

    # Loop over sampled indexes
    for i in idxs:
        image = cv2.imread(data[i]["imagePath"])
        (top, right, bottom, left) = data[i]["loc"]
        face = image[top:bottom, left:right]

        # Resize face and add to faces list
        face = cv2.resize(face, (96, 96))
        faces.append(face)

    # Create montage
    montage = build_montages(faces, (96, 96), (5, 5))[0]

    # Save the output montage
    title = f"Cluster_{labelID}"
    output_path = os.path.join(CLUSTERING_RESULT_PATH, title + '.jpg')
    cv2.imwrite(output_path, montage)

    # Display the montage using matplotlib
    plt.figure(figsize=(6, 6))
    plt.imshow(cv2.cvtColor(montage, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title(title)
    plt.show()

print(f"[INFO] Clustering results saved in {CLUSTERING_RESULT_PATH}")

"""#Saving the Kmeans model"""

# Save the KMeans model to a file
model_save_path = "/kaggle/working/next"
with open(model_save_path, "wb") as f:
    pickle.dump(kmeans, f)

print(f"KMeans model saved to {model_save_path}")

"""#Making predictions with the Kmeans model"""

import pickle
import face_recognition
import matplotlib.pyplot as plt
import matplotlib.image as mpimg

# Load the saved KMeans model
model_load_path = "/kaggle/working/next"
with open(model_load_path, "rb") as f:
    kmeans = pickle.load(f)

def get_face_encoding(image_path):
    # Load the image using face_recognition
    image = face_recognition.load_image_file(image_path)

    # Find the face locations and encodings in the image
    face_locations = face_recognition.face_locations(image)
    face_encodings = face_recognition.face_encodings(image, face_locations)

    if len(face_encodings) > 0:
        return face_encodings[0]  # Return the first face encoding
    else:
        print("No face found in the image.")
        return None

def predict_cluster(image_path, kmeans_model):
    # Get the encoding for the new image
    encoding = get_face_encoding(image_path)

    if encoding is not None:
        # Predict the cluster for the new encoding using the loaded KMeans model
        cluster_label = kmeans_model.predict([encoding])
        return cluster_label[0]
    else:
        return None

# Path to the new image you want to classify
new_image_path = "/kaggle/input/test-d/Clustering_demo_dataset/00000000.jpg"

# Predict the cluster for the new image
cluster_label = predict_cluster(new_image_path, kmeans)

if cluster_label is not None:
    # Display the image along with the predicted cluster
    img = mpimg.imread(new_image_path)
    plt.figure(figsize=(6, 6))
    plt.imshow(img)
    plt.title(f"Cluster: {cluster_label}")
    plt.axis('off')  # Turn off axis
    plt.show()
else:
    print("Cluster prediction failed.")

"""#Using DBSCAN instead of Kmeans"""

# Specify paths
ENCODINGS_PATH = "/content/encodings.pickle"
CLUSTERING_RESULT_PATH = "/kaggle/working/"

# Create Clustering Results directory if it doesn't exist
if not os.path.exists(CLUSTERING_RESULT_PATH):
    os.mkdir(CLUSTERING_RESULT_PATH)

# Load encodings
print("[INFO] loading encodings...")
data = pickle.load(open(ENCODINGS_PATH, "rb"))
data = np.array(data)
encodings = [d["encoding"] for d in data]

# Cluster the embeddings
print("[INFO] clustering...")
clt = DBSCAN(metric="euclidean", n_jobs=-1)
clt.fit(encodings)

# Determine unique label IDs
labelIDs = np.unique(clt.labels_)
numUniqueFaces = len(np.where(labelIDs > -1)[0])
print("[INFO] # unique faces: {}".format(numUniqueFaces))

# Loop over unique face integers
for labelID in labelIDs:
    print("[INFO] faces for face ID: {}".format(labelID))
    idxs = np.where(clt.labels_ == labelID)[0]
    idxs = np.random.choice(idxs, size=min(25, len(idxs)), replace=False)

    # Initialize list of faces
    faces = []

    # Loop over sampled indexes
    for i in idxs:
        image = cv2.imread(data[i]["imagePath"])
        (top, right, bottom, left) = data[i]["loc"]
        face = image[top:bottom, left:right]

        # Resize face and add to faces list
        face = cv2.resize(face, (96, 96))
        faces.append(face)

    # Create montage
    montage = build_montages(faces, (96, 96), (5, 5))[0]

    # Save the output montage
    title = "Face_ID_{}".format(labelID)
    title = "Unknown_Faces" if labelID == -1 else title
    cv2.imwrite(os.path.join(CLUSTERING_RESULT_PATH, title+'.jpg'), montage)

print("Clustering results saved in {}".format(CLUSTERING_RESULT_PATH))

"""#Saving DBSCAN model"""

import pickle

dbscan_model_save_path = "/kaggle/working/dbscan_model.pkl"
with open(dbscan_model_save_path, "wb") as f:
    pickle.dump(clt, f)

print(f"DBSCAN model saved to {dbscan_model_save_path}")

"""#Predictions with DBSCAN model"""

# Load the saved DBSCAN model
dbscan_model_load_path = "/kaggle/working/dbscan_model.pkl"
with open(dbscan_model_load_path, "rb") as f:
    clt = pickle.load(f)

def predict_cluster(image_path, dbscan_model):
    # Get the encoding for the new image
    encoding = get_face_encoding(image_path)

    if encoding is not None:
        # Predict the cluster for the new encoding using the loaded DBSCAN model
        cluster_label = dbscan_model.fit_predict([encoding])
        return cluster_label[0]
    else:
        return None

# Path to the new image you want to classify
new_image_path = "/kaggle/input/wedana/00000072.jpg"

# Predict the cluster for the new image
cluster_label = predict_cluster(new_image_path, clt)

if cluster_label is not None:
    print(f"The new image belongs to cluster: {cluster_label}")
else:
    print("Cluster prediction failed.")

!pip install face_recognition deepface opencv-python-headless imutils scikit-learn matplotlib

import os
import cv2
import pickle
import numpy as np
import matplotlib.pyplot as plt

from deepface import DeepFace
from imutils import paths, build_montages
from sklearn.cluster import KMeans, DBSCAN
import face_recognition

# Define dataset paths
dataset_path = "/kaggle/input/test-d"
encodings_path = "/content/emotion_encodings.pickle"

# Initialize dataset storage
data = []
imagePaths = list(paths.list_images(dataset_path))

for (i, imagePath) in enumerate(imagePaths):
    print(f"[INFO] Processing image {i + 1}/{len(imagePaths)}: {imagePath}")

    # Read the image
    image = cv2.imread(imagePath)
    rgb_image = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)

    # Detect faces
    boxes = face_recognition.face_locations(rgb_image, model='hog')

    # Compute facial encodings
    encodings = face_recognition.face_encodings(rgb_image, boxes)

    # Extract emotion using DeepFace
    try:
        emotion_result = DeepFace.analyze(imagePath, actions=['emotion'], enforce_detection=False)
        emotion = emotion_result[0]['dominant_emotion']
    except:
        emotion = "unknown"

    # Store encodings and emotions
    for (box, enc) in zip(boxes, encodings):
        data.append({"imagePath": imagePath, "loc": box, "encoding": enc, "emotion": emotion})

    # Draw face boxes
    for (top, right, bottom, left) in boxes:
        cv2.rectangle(rgb_image, (left, top), (right, bottom), (0, 255, 0), 3)

    # Display images with detected faces
    plt.figure(figsize=(6, 6))
    plt.imshow(rgb_image)
    plt.axis("off")
    plt.title(f"Emotion: {emotion}")
    plt.show()

# Save encodings
with open(encodings_path, "wb") as f:
    pickle.dump(data, f)

print(f"[INFO] Encodings saved to: {encodings_path}")

# Load encodings
ENCODINGS_PATH = "/content/emotion_encodings.pickle"
print("[INFO] Loading encodings...")
data = pickle.load(open(ENCODINGS_PATH, "rb"))

# Extract identity encodings and emotions
encodings = np.array([d["encoding"] for d in data])
emotions = np.array([d["emotion"] for d in data])

# Perform KMeans clustering on facial identity
print("[INFO] Clustering faces...")
kmeans_faces = KMeans(n_clusters=5, random_state=42, n_init=10)
face_labels = kmeans_faces.fit_predict(encodings)

# Perform KMeans clustering on emotion labels
unique_emotions = list(set(emotions))
emotion_labels = np.array([unique_emotions.index(e) for e in emotions])

kmeans_emotions = KMeans(n_clusters=len(unique_emotions), random_state=42, n_init=10)
emotion_clusters = kmeans_emotions.fit_predict(emotion_labels.reshape(-1, 1))

print(f"[INFO] Unique faces detected: {len(np.unique(face_labels))}")
print(f"[INFO] Unique emotion clusters detected: {len(np.unique(emotion_clusters))}")

for labelID in np.unique(face_labels):
    print(f"[INFO] Faces for cluster: {labelID}")
    idxs = np.where(face_labels == labelID)[0]
    idxs = np.random.choice(idxs, size=min(25, len(idxs)), replace=False)

    faces = []
    for i in idxs:
        image = cv2.imread(data[i]["imagePath"])
        (top, right, bottom, left) = data[i]["loc"]
        face = image[top:bottom, left:right]
        face = cv2.resize(face, (96, 96))
        faces.append(face)

    montage = build_montages(faces, (96, 96), (5, 5))[0]

    plt.figure(figsize=(6, 6))
    plt.imshow(cv2.cvtColor(montage, cv2.COLOR_BGR2RGB))
    plt.axis("off")
    plt.title(f"Face Cluster {labelID}")
    plt.show()

# Save models
with open("/kaggle/working/kmeans_faces.pkl", "wb") as f:
    pickle.dump(kmeans_faces, f)

with open("/kaggle/working/kmeans_emotions.pkl", "wb") as f:
    pickle.dump(kmeans_emotions, f)

print("Models saved successfully!")

def predict_cluster(image_path, kmeans_model):
    encoding = face_recognition.face_encodings(face_recognition.load_image_file(image_path))[0]
    return kmeans_model.predict([encoding])[0]

new_image_path = "/kaggle/input/wedana/00000072.jpg"

with open("/kaggle/working/kmeans_faces.pkl", "rb") as f:
    kmeans_faces = pickle.load(f)

face_cluster = predict_cluster(new_image_path, kmeans_faces)
print(f"Predicted Face Cluster: {face_cluster}")